#!/bin/bash

PRIVATEKEY="Your20CharsLongPrivateKey"
#PRIVATEKEY="OrYour15CharsLongAliasKey"
MESSAGE="$1"
TITLE="$2"
DEVICE="$3"
ICON="$4"
SOUND="$5"
VIBRATION="$6"
URL="$7"
URLTITLE="$8"
TIME2LIVE="$9"
PRIORITY="$10"
RETRY="$11"
EXPIRE="$12"
CONFIRM="$13"
ANSWER="$14"
ANSWEROPTIONS="$15"
ANSWERFORCE="$16"

curl https://www.pushsafer.com/api -d k="$PRIVATEKEY" -d m="$MESSAGE" -d t="$TITLE" -d d="$DEVICE" -d i="$ICON" -d s="$SOUND" -d v="$VIBRATION" -d u="$URL" -d ut="$URLTITLE" -d l="$TIME2LIVE" -d pr="$PRIORITY" -d re="$RETRY" -d ex="$EXPIRE" -d cr="$CONFIRM" -d a="$ANSWER" -d ao="$ANSWEROPTIONS" -d af="$ANSWERFORCE"
